### ISSUE TITLE
1D-recycling example crashes when run in parallel

### ISSUE THREAD

**Issue by mikekryjak** [bendudson/hermes-3#124]
Ran 1D-recycling with the default settings:

> [solver]
type = beuler  # Backward Euler steady-state solver
snes_type = newtonls
ksp_type = gmres
max_nonlinear_iterations = 10

This crashes after 364 out of the 400 iterations when running in parallel on 10 cores. There is a standard error message:
`Error encountered in solver run`
`Solver failed after many attempts`

When Hypre is enabled:

> [solver]
type = beuler  # Backward Euler steady-state solver
snes_type = newtonls
ksp_type = gmres
max_nonlinear_iterations = 10
pc_type = hypre

The case crashes after only 8 iterations with the same error.
It runs fine with beuler on 1 core (default settings).

Thanks @tbody-cfs for flagging this up.
@bendudson have you done much testing of the example cases with Hypre? I have almost never run with it myself.

**Comment by bendudson** [comment]
The short answer to this seems to be that hypre's default BoomerAMG solver doesn't work well for this problem. Other solvers in hypre work much better, in particular `pilut` and `euclid`. Given how well ILU works in serial, it's no surprise that these are variations on parallel ILU algorithms. 

There's a PETSc flag `-pc_hypre_type` (https://petsc.org/release/manualpages/PC/PCHYPRE/) to set the type of hypre solver:
```
mpirun -np 8 ./hermes-3 -d examples/1D-recycling input:error_on_unused_options=false -pc_hypre_type pilut
```
Note that we have to disable the BOUT++ input typo checking so that it doesn't complain about the arguments that it doesn't recognise.

In this branch https://github.com/boutproject/BOUT-dev/pull/2716 I've added a BOUT++ option `pc_hypre_type` with default value `pilut`.

**Comment by mikekryjak** [comment]
Resolved by changing Hypre to `euclid`
