### ISSUE TITLE
The problem of particle flux of 1D simulations

### ISSUE THREAD

**Issue by lqs661** [bendudson/hermes-3#218]
When I runned the isotope 1D cases, the particle flux directly output by the program is "scaled" by the isotope mass. For example, the particle flux of tritium is "3*n*v" not "n*v". The detailed results are shown as follows:
![image](https://github.com/bendudson/hermes-3/assets/111937551/d64f4ce6-3bba-408e-9b5d-5aef9c7ef9c8)
I have made the density scan of pure H/D/T situation. The left figure shows the results output by the program, and the right figure shows  the results calculated by "Γ=n*v". The command output the particle flux is 'collect('X', tind=-1)[-1,0,1:-1,0]', and 'X' means 'NVh+', 'NVd+' or 'NVt+'. Maybe this is a bug of hermes-3?

**Comment by bendudson** [comment]
Hi @lqs661 ! Thanks yes, this is supposed to happen. Sorry, the name of the variable is not very good: "NV" should really be called "mNV" because it's the parallel momentum, not the parallel flux. Divide by amu (1, 2, 3...) to get the flux.

One way to check things like this is to check the attributes in the output files e.g. 
```
	double NVi(t, x, y, z) ;
		NVi:current_time_index = 177 ;
		NVi:cell_location = "CELL_CENTRE" ;
		NVi:conversion = 0.00115754821119734 ;
		NVi:description = "" ;
		NVi:direction_y = "Standard" ;
		NVi:direction_z = "Standard" ;
		NVi:long_name = "i parallel momentum" ;
		NVi:source = "evolve_momentum" ;
		NVi:species = "i" ;
		NVi:standard_name = "momentum" ;
		NVi:time_dimension = "t" ;
		NVi:units = "kg / m^2 / s" ;
```
This has a description, and the SI units. The "conversion" factor is the number to multiply by to convert the numbers stored in the output file into SI units.

Sorry for the confusion! We should change the name of the variable. Thanks for trying out Hermes-3!
